title: "Header"
description: |
  Organize the top of the page.
paterns:
  header:
    title: "Header"
    description: |
      Will be used at the top of the page and will allow users to easily navigate around the website organized into the four main groups of the website.
