title: "Banners"
description: |
  Banners will draw the viewers into the website and create a visual representation of Bijou Brine

patterns:
  banner-dark-card:
    title: "Banner Dark Card"
    height: 300
    fields:
      - name: heading
        type: string
        example: "Pickle Your Life"
      - name: image
        type: image
        example: "picklebanner.jpg"
      - name: button_text
        type: string
        example: "Shop Now"
        required: false
    description: |
      This banner will be used on the inital landing and products page. The image, title and details will change based on what page it is on.

  banner-light-card:
    title: "Banner Light Card"
    fields:
      - name: heading
        type: string
        example: "What's the Dill?"
      - name: details
        type: string
        example: "Sign up with your email address to recieve news and updates"
      - name: button_text
        type: string
        example: "Shop Now"
        required: false
      - name: image
        type: image
        example: "bottlebanner.jpg"
    description: |
      This banner will be used on the merchandise landing page and will guide users to buy things.
